extends: airbnb

settings:
  import/resolver: babel-root-import

env:
  node: true

parser: "babel-eslint"

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  react/jsx-filename-extension:
    - 0
  react/forbid-prop-types:
    - 0
  import/prefer-default-export:
    - 0
  import/extensions:
    - 2
    - never
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxEOF: 0
  comma-dangle:
    - error
    - never
  max-len:
    - 2
    - code: 150
  no-confusing-arrow:
    - error
    - allowParens: true
  no-use-before-define: off
  eol-last: error
